### ISSUE TITLE
Why isn't the theme working for the lock screen?

### ISSUE THREAD

**Issue by francoism90** [Eayu/sddm-theme-clairvoyance#9]
Thanks for creating this SSDM theme, really like it. :+1: 

Is it normal that the theme isn't applied to the lock screen? Is this Plasma/KDE related?

Thanks!

**Comment by eayus** [comment]
Sorry for stupidly late reply, I must've missed this email. I'm not exactly sure on how KDE manages lock screens, since SDDM on its own doesn't seem to support this. It seems like the personalisation on the KDE lock screen is limited to changing the wallpaper only (supposedly accessible through the settings program, I haven't tested this however).
